version: '3.7'
services:
  php-fpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    volumes:
      - .:/app:cached
    working_dir: /app
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - php-fpm
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume:
